### PR TITLE
fix: Made installable.

### PR DESCRIPTION
**Pull request by hidao80**
The box is not specified and can not be installed.

### CODE REVIEW

**Comment by hidao80** [comment]
@KEINOS 

Could not install with "Vagrant up" because box is not specified.
We can respond with this pull request.

**Review by KEINOS — CHANGES_REQUESTED** [review]
Good point, the specific the better!
But since v0.0.3 was already released will you create a new 'Vagrantfile_v0.0.4' for it?

**Comment by KEINOS** [comment]
@hidao80 

I'll do the new file (v0.0.4) creation to this PR.

**Comment by KEINOS** [comment]
@hidao80 

macOS HighSierra Base box v0.0.4 released! Thanks!

https://app.vagrantup.com/KEINOS/boxes/macOS.10.13.6_Japanese/versions/0.0.4

**Pull request merged**
